[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/password-check.html"
  status = 200
  force = false

[context.production.environment]
  SITE_PASSWORD = "your-password-here"
